version: '3.1'

services:
  springboot:
    image: jitendra7829/spring-boot-mongo:$BUILDNO
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
     - 8080:8080
    depends_on:
     - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    volumes:
     - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:

networks:
  springappnetwork:
